first_name = input("please enter your name:")
last_name = input("please enter your name:")
print("hello",first_name, last_name, "nice to meet you!")
first_name = input("please enter your first name:")
last_name = input("please enter your last name:")
age = input("how old are you" + first_name + '?')
print("hello", first_name, last_name," nice to meet you!")
print(first_name, 'you were born in the year', 2023-int(age))